name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker image
        run: |
          docker build -t briac596/house-price-api:lastest .
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push briac596/house-price-api:lastest

      - name: Install sshpass and deploy
        run: |
          sshpass -p "Supermotdepasse!42" ssh -o StrictHostKeyChecking=no ubuntu@20.86.55.5 "
            docker pull briac596/house-price-api:latest &&
            docker rm -f my_app_container || true &&
            docker run -d --name my_app_container -p 8081:8000 briac596/house-price-api:latest"

